### ISSUE TITLE
Application crashes right away when trying to use lwk-rn

### ISSUE THREAD

**Issue by dev4bitcoin** [Blockstream/lwk-rn#3]
I am building the React native app and using lwk-rn to access Liquid wallet library. The problem is when i try to use signer or client, the app right away crashes. There is no error message. 

it happens in the following line. Anytime if i try to use new Signer() or new Client(), app crashed without any error message.

const signer = await new Signer().create(mnemonic, network);
or
const client = await new Client().defaultElectrumClient(network);

I imported this project and ran example and it works fine. However, when i try to use it in my app, it wont work.

Am i missing something? Is it a packaging issue? I banging my head for past few days. Any help is appreciated.

**Comment by lvaccaro** [comment]
Hi @dev4bitcoin , thanks to open the issue!

which platform do you use for the example?

On ios platform, the lwk cocoapods package could not be updated good. I reproduce the crash, and it looks fixed by passing `--force-pods` flag. 

You could find an react native example app at `https://github.com/lvaccaro/lwk-rn-example`.

**Comment by dev4bitcoin** [comment]
Thank you. Running '--force-pods' fixed the issue. Not sure why dependencies not installed when i ran 'pod install'.
